#!/bin/bash

usage() {
    echo "Использование: pkg <менеджер> <команда> <пакеты>"
    echo "Команды: install, remove, list, search"
    echo "Менеджеры: pacman, yay, snap"
    echo "Пример: pkg pacman install vim,git,nano"
    echo "        pkg yay list"
    echo "        pkg pacman search neofetch"
    exit 1
}

MANAGER="$1"
CMD="$2"
PKGS="$3"

IFS=',' read -ra PACKAGES <<< "$PKGS"

case "$MANAGER" in
    pacman)
        case "$CMD" in
            install)
                sudo pacman -S "${PACKAGES[@]}"
                ;;
            remove)
                sudo pacman -Rns "${PACKAGES[@]}"
                ;;
            list)
                pacman -Qq
                ;;
            search)
                pacman -Ss "$PKGS"
                ;;
            *)
                usage
                ;;
        esac
        ;;
    yay)
        case "$CMD" in
            install)
                yay -S "${PACKAGES[@]}"
                ;;
            remove)
                yay -Rns "${PACKAGES[@]}"
                ;;
            list)
                yay -Qq
                ;;
            search)
                yay -Ss "$PKGS"
                ;;
            *)
                usage
                ;;
        esac
        ;;
    snap)
        case "$CMD" in
            install)
                sudo snap install "${PACKAGES[@]}"
                ;;
            remove)
                sudo snap remove "${PACKAGES[@]}"
                ;;
            list)
                snap list | tail -n +2 | awk '{print $1}'
                ;;
            search)
                snap find "$PKGS"
                ;;
            *)
                usage
                ;;
        esac
        ;;
    *)
        usage
        ;;
esac